### ISSUE TITLE
如何让circle ci只执行特定分支

### ISSUE THREAD

**Issue by any86** [any86/Notes#29]
```
version: 2
jobs:
  build:
    branches:
      only:
          - master
```

或者

version: 2
jobs:
  build:
    branches:
      ignore:
          - xxx
          - xxx

或者
提交信息中包含"[ci skip]"
